# PR 이벤트 발생 시(opened), 라벨이 붙는 이벤트 발생 시(labeled) 자동으로 팀원 중 Reviewer 2명 지정
name: 'Auto Assign Reviewers'

on:
  pull_request:
    types: [opened, labeled]

jobs:
  assign_reviewers:
    runs-on: ubuntu-latest
    steps:
      - name: 'Check for label'
        uses: actions/github-script@v6
        id: label_check
        with:
          script: |
            const labels = context.payload.pull_request.labels;
            return labels.some(label => label.name === '확인 요청');
      - name: 'Assign Reviewers'
        if: steps.label_check.outputs.result == 'true'
        uses: kentaro-m/auto-assign-action@v1
        with:
          reviewers: |
            effozen
            happyhyep
            juwon5272
            leedongyull
          number_of_reviewers: 2