name: CI - Lint, Build, and Test with pnpm

on:
  pull_request:
    branches:
      - '*'  # 모든 브랜치에서 PR 생성 시 동작

jobs:
  lint-build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # 프로젝트에 맞는 Node.js 버전 지정

      - name: Install pnpm
        run: npm install -g pnpm  # pnpm 설치

      - name: Install Dependencies
        run: pnpm install  # pnpm을 사용하여 의존성 설치

      - name: Run Linter
        run: pnpm lint  # pnpm을 사용하여 린트 실행
        continue-on-error: false # 린트 실패 시 워크플로우 실패로 처리

      - name: Run Build
        run: pnpm build  # pnpm을 사용하여 빌드 실행
        continue-on-error: false # 빌드 실패 시 워크플로우 실패로 처리

      - name: Run Tests
        run: pnpm test  # pnpm을 사용하여 테스트 실행
        continue-on-error: false # 테스트 실패 시 워크플로우 실패로 처리
